### PR TITLE
Add a real in practice example for Android Studio users.

### PR DESCRIPTION
**Pull request by lancewoo**
Hi @saudet ,

I just included a real library project for those Android developers' help. Feel free to merge in. Please tell me if you have questions.
Thanks for your great work!

Lance

### CODE REVIEW

**Comment by saudet** [comment]
Looking good, thanks! Since this looks mostly like C++ files that we can get from another repository though, could you add a script to download them, possibly based on the one done for the zlib sample project here?
https://github.com/bytedeco/gradle-javacpp/blob/master/samples/zlib/build.sh

**Comment by lancewoo** [comment]
> 
> 
> Looking good, thanks! Since this looks mostly like C++ files that we can get from another repository though, could you add a script to download them, possibly based on the one done for the zlib sample project here?
> https://github.com/bytedeco/gradle-javacpp/blob/master/samples/zlib/build.sh

There are some minor modifications to the source code. Check this issue: [https://github.com/LAStools/LAStools/issues/112](url)  What I suggested in that issue was not wholely adopted so I have to edit that manually. Or else I'd suggest again.

For this sample project, I'd suggest a merge-in.
And also I'll have a try at your suggestion.

Thanks!
Lance

**Comment by saudet** [comment]
We can perform minor modifications like that with diff, sed, etc. Please
try to do that.

**Comment by lancewoo** [comment]
> 
> We can perform minor modifications like that with diff, sed, etc. Please try to do that.

Please check this request https://github.com/bytedeco/gradle-javacpp/pull/18 .

**Comment by saudet** [comment]
Let's keep that sample project here, that's fine.

**Comment by lancewoo** [comment]
Hi @saudet , I just updated this request. Please tell me if it still needs some change. Thanks.

**Comment by saudet** [comment]
I still see the source code of LASlib itself in there. Could you remove it and have it downloaded at build time like you did in https://github.com/bytedeco/gradle-javacpp/pull/18? Thanks!

**Comment by lancewoo** [comment]
> 
> 
> I still see the source code of LASlib itself in there. Could you remove it and have it downloaded at build time like you did in [bytedeco/gradle-javacpp#18](https://github.com/bytedeco/gradle-javacpp/pull/18)? Thanks!

Done now.

**Pull request merged**
