### PR TITLE
Example of using JavaCPP Presets for Caffe

### PR DESCRIPTION
**Pull request by Undin**
Java version of original C++ example of caffe usage https://github.com/BVLC/caffe/tree/master/examples/cpp_classification

### CODE REVIEW

**Comment by saudet** [comment]
Thanks! Looks fine, but I don't think we need to bundle Gradle?

**Comment by Undin** [comment]
I usually prefer gradle as build system, but if you really want to use maven I'll fix it.

**Comment by saudet** [comment]
No, Gradle is fine, I'm just wondering if we need to put a binary JAR file in the source repository. Is this common practice?

**Comment by Undin** [comment]
Yes, it's common practice. This jar isn't jar of gradle build system, it's only part of gradle wrapper - tool for building gradle projects without installed gradle. User can run this wrapper and it will download the appropriate version of gradle and build a project. You can get more details [here](https://docs.gradle.org/current/userguide/gradle_wrapper.html).

**Comment by saudet** [comment]
Ah, ok, that's good then. Thanks for the contribution!

**Pull request merged**
