### PR TITLE
added CUDA example

### PR DESCRIPTION
**Pull request by ka-ba**

### CODE REVIEW

**Comment by saudet** [comment]
Thanks! Let's also add a small pom.xml like this one to complete this?
https://github.com/bytedeco/javacpp-presets/tree/master/cuda#the-pomxml-build-file

**Comment by ka-ba** [comment]
second commit is not yet tested on a machine with CUDA-HW - will have to wait till Monday

**Comment by saudet** [comment]
It sort of works on my machine:
```
result incorrect at position 999997: expected -734379956, but got -733379958
```

**Comment by ka-ba** [comment]
OK, working as expected. ;)
from the readme: "There's a deliberate error introduced into one of the input vectors to show that the check really checks and that all other values are as expected."
from the code: "a[N-3]=1; // introduce error to be found; to show that check works"
Thanks for testing! :+1:

**Pull request merged**
