### PR TITLE
update project with cmake way.

### PR DESCRIPTION
**Pull request by leaf918**

### CODE REVIEW

**Comment by saudet** [comment]
Could stop creating duplicate pull requests, keep one of them, and fix it please?

**Comment by leaf918** [comment]
accept this pull request ,and ignore others.

**Comment by saudet** [comment]
So, please fix it by removing all the executable bits.

**Comment by saudet** [comment]
The mode on all the files are changed from 644 to 755. Could you please revert that?

**Comment by saudet** [comment]
I've made the necessary changes. Can you confirm that this project works as intended and fixes https://github.com/bytedeco/javacpp/issues/205? And then I'll merge this. Thanks!!

**Comment by leaf918** [comment]
confirm.

**Comment by saudet** [comment]
Thanks!

**Pull request merged**
